_commit: 99922d5
_src_path: https://github.com/slaclab/lume-model-deployment-template.git
deployment_name: lcls-cu-inj-model-deployment
device: cpu
inference_service_url: http://inference-service-cu-inj:8000
interface: epics
mlflow_tracking_uri: https://ard-mlflow.slac.stanford.edu/
model_version: 1
rate: 1.0
registered_model_name: lcls-cu-inj-model
